version: "3.4"

services:
  udemy-app:
    build: .
    restart: always
    ports:
      - 3000:80
    volumes:
      - app_data:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  app_data:
  node_modules:
